### ISSUE TITLE
Report ZPHISHER Clone

### ISSUE THREAD

**Issue by grm34** [Akshay-Arjun/69phisher#3]
Hmm it's hdr-tech Zphisher and you renamed as your project?

**Comment by Akshay-Arjun** [comment]
Yes. Didn't you read README ?

**Comment by grm34** [comment]
Few changes? Logo and readme... Forks exist for that. Reported to hdr-tech

**Comment by Akshay-Arjun** [comment]
> yeah I know that. and I'm working on BITB attack. to add BITB TO THIS DOESN'T need a fork and need a rewrite.
The only thing i need from htr tech is cloudflared and menu.  I can get those even from others ;). Peace out man. Will ping when it's complete. Learn more about BITB attack [here](https://www.makeuseof.com/what-is-browser-in-the-browser-attack/)

**Comment by Akshay-Arjun** [comment]
> yeah I know that. and I'm working on BITB attack. to add BITB TO THIS DOESN'T need a fork and need a rewrite.
The only thing i need from htr tech is cloudflared and menu.  I can get those even from others ;). Peace out man. Will ping when it's complete. Learn more about BITB attack [here](https://www.makeuseof.com/what-is-browser-in-the-browser-attack/) and [here](https://github.com/mrd0x/BITB)

**Comment by grm34** [comment]
Incredible answer... YOU must learn from scratch... Peace out

**Comment by Akshay-Arjun** [comment]
Lol. Looks like you never heard of using things in the license they provide. Completely pissed off at nothing 🤣.

**Comment by grm34** [comment]
Sooooo.... Still waiting your rewrite xD...
