### ISSUE TITLE
Credentials 

### ISSUE THREAD

**Issue by Jaynunez1984** [Akshay-Arjun/69phisher#7]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Where is the credentials stored? Or do i have to keep termux open untill the person opens link and enters credentials? And can I send link so other person can forward it tI another person

**Comment by Akshay-Arjun** [comment]
1) The creditionals will be displayed on screen when the victim opens link and enter them. And also all the creditionals will be stored in a file. 
2) Please keep termux in background, do not close it. 
3) The link can be shared to many persons at a time and it can also be forwarded to other person from another person.
