### ISSUE TITLE
url is bad

### ISSUE THREAD

**Issue by merci20** [Akshay-Arjun/69phisher#8]
the url is not displayed in full.
need an update

**Comment by Akshay-Arjun** [comment]
Any screenshot and steps to reproduce

**Comment by merci20** [comment]
sorry, mistake on my part
Its happening now.
Thank you for answering

**Comment by merci20** [comment]
Your templates are great. If you allow me I would like to make some recommendations that you could add: like you could add another page regarding airbnb or google like a fake password change page and you could also allow the user to redirect the urls themselves. on top Congratulations for the work already done
