### ISSUE TITLE
problem with clouadflare

### ISSUE THREAD

**Issue by aminsangbori** [Akshay-Arjun/69phisher#9]
im problem with clouadflare

┌──(unknown㉿kali)-[~/69phisher]
└─$ bash 69phisher.sh
mkdir: cannot create directory ‘.server’: Permission denied
mkdir: cannot create directory ‘.server’: Permission denied

[+] Installing required packages...

[+] Packages already installed.

[+] Installing Cloudflared...

[!] Error occured, Install Cloudflared manually.

**Comment by Akshay-Arjun** [comment]
Please give permissions. Before execution. 
1) ``` chmod 777 69phisher.sh```
2) ``` bash 69phisher.sh ```
